#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export DOCKER_HOST=tcp://localhost:2375
export PATH="bin:/Users/sbusso/.rbenv/shims:/Users/sbusso/.rbenv/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"

eval "$(rbenv init -)"
source ~/.docker-env

export SHELL=/bin/zsh
unalias rm

source ~/.docker-stage

